version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Set context to the frontend directory
      dockerfile: Dockerfile  # Dockerfile is now within the context
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    networks:
      - pokeApi

  backend:
    build: ./backend
    container_name: backend_pokeApi
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/pokemonDB
      - POKE_API_URL=https://pokeapi.co/api/v2/pokemon
      - PORT=4000
    networks:
      - pokeApi
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pokeApi

volumes:
  mongo_data:

networks:
  pokeApi:
    driver: bridge