services:
  backend:
    build: .
    container_name: backend_pokeApi
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/pokemonDB
    networks:
      - pokeApi
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pokeApi

volumes:
  mongo_data:

networks:
  pokeApi:
    driver: bridge
